from ccxt_satis.base.types import Entry


class ImplicitAPI:
    public_get_time = publicGetTime = Entry('time', 'public', 'GET', {})
    public_get_currencies = publicGetCurrencies = Entry('currencies', 'public', 'GET', {})
    public_get_product = publicGetProduct = Entry('products', 'public', 'GET', {})
    public_get_long_short_ratio = publicGetLongShortRatio = Entry('products/long_short_ratio', 'public', 'GET', {})
    public_get_open_interest = publicGetOpenInterest = Entry('products/open_interest', 'public', 'GET', {})
    public_get_order_book = publicGetOrderBook = Entry('products/{product_id}/book', 'public', 'GET', {})
    public_get_ticker = publicGetTicker = Entry('products/{product_id}/ticker', 'public', 'GET', {})
    public_get_trades = publicGetTrades = Entry('products/{product_id}/trades', 'public', 'GET', {})
    public_get_candles = publicGetCandles = Entry('products/{product_id}/candles', 'public', 'GET', {})
    public_get_stats = publicGetStats = Entry('products/{product_id}/stats', 'public', 'GET', {})
    public_get_indices = publicGetIndices = Entry('indices', 'public', 'GET', {})
    private_get_accounts = privateGetAccounts = Entry('accounts', 'private', 'GET', {})
    private_get_account_ledger = privateGetAccountLedger = Entry('accounts/{account_id}/ledger', 'private', 'GET', {})
    private_get_holds = privateGetHolds = Entry('accounts/{account_id}/holds', 'private', 'GET', {})
    private_get_fills = privateGetFills = Entry('fills', 'private', 'GET', {})
    private_get_fees = privateGetFees = Entry('fees', 'private', 'GET', {})
    private_get_orders = privateGetOrders = Entry('orders', 'private', 'GET', {})
    private_get_order = privateGetOrder = Entry('orders/{order_id}', 'private', 'GET', {})
    private_get_position = privateGetPosition = Entry('positions/{product_id}', 'private', 'GET', {})
    private_post_order = privatePostOrder = Entry('orders', 'private', 'POST', {})
    private_post_position_cross = privatePostPositionCross = Entry('positions/cross', 'private', 'POST', {})
    private_post_position_isolate = privatePostPositionIsolate = Entry('positions/isolate', 'private', 'POST', {})
    private_post_position_margin = privatePostPositionMargin = Entry('positions/margin', 'private', 'POST', {})
    private_post_position_risk = privatePostPositionRisk = Entry('positions/risk', 'private', 'POST', {})
    private_delete_orders = privateDeleteOrders = Entry('orders', 'private', 'DELETE', {})
    private_delete_order = privateDeleteOrder = Entry('orders/{order_id}', 'private', 'DELETE', {})
